### ISSUE TITLE
How to get an Identity Token issued by https://confidentialcomputing.google.com

### ISSUE THREAD

**Issue by Ori-b** [salrashid123/confidential_space#1]
Great Guide salrashid!
I have trying for days figuring out how to get an identity token for my operator confidential vm, which is issued by https://confidentialcomputing.googleapis.com/  with my confidential vm attestation data
It is also missing from google labs and documentation.
Will appreciate very much for a direction or hint,
currently I am working with identity tokens issued by accounts.google.com (gcloud auth print-identity-token) but I fail to set my custom claims (digest and so forth)
Thanks in advance !!
![image](https://user-images.githubusercontent.com/105278211/218747998-cb63d384-3656-49bc-b0b3-d7df353de015.png)

**Comment by salrashid123** [comment]
the token is mounted to the runtime container as a file at
`/run/container_launcher/attestation_verifier_claims_token`

meaning, you can read it in directly:
https://github.com/salrashid123/confidential_space/blob/main/app/main.go#L59

or use it as part of workload federation 

https://github.com/salrashid123/confidential_space/blob/main/app/main.go#L152

**Comment by Ori-b** [comment]
Thanks for your reply!
My confidential VM (GCP) has nothing of that sort in that path, i.e. container_launcher (see image below after running 
"ls /run" )
 What confidential set up are you using ? ..  any thoughts ?
 Thanks in advance.
 
![image](https://user-images.githubusercontent.com/105278211/218777224-95faa94c-f117-4eb2-9ed7-3e0c18846412.png)

**Comment by salrashid123** [comment]
to backtrack a bit as there maybe some confusion here...this git repo doens't describe how to setup generic confidentiality on  gcp but describes how to use the  GCP product 
[Confidential Space](https://cloud.google.com/blog/products/identity-security/announcing-confidential-space).

a confidential space VM is a specific type of  GCP vm in which you run a docker container (think of it as a product).

the conf space VM google provides  includes  set degree of security guarantees (ssh is disabled, its id_token will identify the specific docker image hash thats running and in what context, etc.  THose gurantees can be use to access data from different collaborators such that nobody (not even the owner of the conf. space VM can access/see that info)

**Comment by Ori-b** [comment]
Thanks salrashid, 
That is exactly my case, I am using a Confidential Space VM, running my workload as a docker container, 
and my workload, as you specified in this guide( my container's code), is trying to read this attestation_verifier_claims_token from the path:
/run/container_launcher/attestation_verifier_claims_token , but to no avail.
Apparently it is not on my machine or running container (peeked inside also).
so here is my dilemma, what are you doing different (setup wise) ?
Greatly appreciate your effort.

**Comment by salrashid123** [comment]
i verified the instructions in this repo earlier today.; ou'll need to follow it pretty precisely...

when you launch vm, you need to specify the image, image familiy, etc

inmycase, i'm using the debug image set

```
  --image-project=confidential-space-images \
  --image-family=confidential-space-debug 
```

````
gcloud compute instances create vm1 --confidential-compute \
  --shielded-secure-boot \
  --maintenance-policy=TERMINATE --scopes=cloud-platform  --zone=us-central1-a \
  --image-project=confidential-space-images \
  --image-family=confidential-space-debug --network=teenetwork --no-address \
  --service-account=operator-svc-account@$OPERATOR_PROJECT_ID.iam.gserviceaccount.com \
  --metadata ^~^tee-image-reference=us-central1-docker.pkg.dev/$BUILDER_PROJECT_ID/repo1/myimage@sha256:913831ec02a1449db2560872360499795b8985ae2068625589ca705fcf2366d0~tee-restart-policy=Never~tee-container-log-redirect=true

```

**Comment by Ori-b** [comment]
Thanks a lot !!!!
I've recreated the confidential vm with the following: 
....
--image-project=confidential-space-images \
--image-family=confidential-space-debug \
....
But now I run into a new wall:
1. Who is suppose to run my container (long running) ? is it automatically run at creation of the instance ?
or should I run it explicitly : "docker run ...."
2. Who can access the image provided ? (the specified service-account on creation of the instance has permissions to the relevant artifact registry but from the VM itself "ssh-ing" I can't 'docker pull' )
3. How can I validate that it is running ("docker ps" shows nothing runing at all) 
4. How can I see the logs if it fails ?
5. How much significant the following on creation "--network=teenetwork --no-address"

Thanks

**Comment by salrashid123** [comment]
the VM is a type of [container optimized os](https://cloud.google.com/container-optimized-os/docs)  which is designed to automatically execute the `docker run` equivalent command on boot

it will load and run the default entrypoint of the container image you specified in the gcloud command `tee-image-reference=` variable

note, you're not supposed to get access to the container or the VM (thats a point of the conf-space vms).   the git repo here uses the `debug` image which does allow ssh and stdout logging but thats just for a demo

**Comment by Ori-b** [comment]
Thanks for your great efforts !
I got to the point where I can see the VM trying to launch the container with the specified image , and except on the ground of the OIDC... 
<img width="755" alt="image" src="https://user-images.githubusercontent.com/105278211/219083532-6889d96e-26eb-4f30-8b2d-e56e89b4a0b8.png">

![image](https://user-images.githubusercontent.com/105278211/219084353-f28fd1b5-d893-437d-b2a4-41c5b282edbe.png)


I would whole heartedly appreciate your
 wise help :) !

**Comment by salrashid123** [comment]
this error usually means that the TPM failed AUTH too many times (i.e. rate limiting type of protection).

The suggestion would be to create a fresh Confidential Space VM (instead of rebooting/resetting).

**Comment by Ori-b** [comment]
Thanks you are the Best !
My confidential container is up and running ,
Thanks for you patience and dedicated help, 

It's not directly connected to your guide,
but maybe you will know ? 
my workload exposes an endpoint on port 3000, 
Is there anyway on the creation of the confidential VM instance (flags or meta data) 
to allow access to this port from outside of the VM ? 
( As like when mapping the port to the network host port - i.e. using docker-compose directive Port 3000:3000 ....)

**Comment by salrashid123** [comment]
glad to hear its working;   confidential space does not support inbound listening sockets yet.

do you have a google cloud account manager or sales engineer your'e working with?  if so, could you reach out to them to ask them to contact the Conf-Space VM product team listed in this announcement [here](https://cloud.google.com/blog/products/identity-security/announcing-confidential-space)  (i.,e rene) .   THat channel may give you more insight (and for the product team to learn of your usecase).

**Comment by Ori-b** [comment]
I would certainly address it further... :), 
But just to clarify your remark : 
![image](https://user-images.githubusercontent.com/105278211/219377293-9716c601-88da-4b65-a37f-562f01538df3.png)
How does it settles with me being able to get a response from the workload endpoint when accessing it directly from inside the VM ? how is that port accessible to me from within?

**Comment by salrashid123** [comment]
well, you certainly can make an 'outbound' request from within the container to anywhere (eg workload federation url, google api, amazon api, any endpoint).  once the outbound connection is made, you can recieve traffic on that socket only.

someone outisde can't unilaterally connect or create a new connection to the container. (i.,e you can't run a webserver inside the cotnainer at the moment but you can contact a webserver outside somewhere from the container)

**Comment by Ori-b** [comment]
Thanks a lot for all you kind help !!!
